import type { App } from "vue";
import { defineAsyncComponent } from "vue";

const iconLoaders = [
  ["i-api", () => import("@icon-park/vue-next/es/icons/Api")],
  ["i-application-menu", () => import("@icon-park/vue-next/es/icons/ApplicationMenu")],
  ["i-arrow-up", () => import("@icon-park/vue-next/es/icons/ArrowUp")],
  ["i-attention", () => import("@icon-park/vue-next/es/icons/Attention")],
  ["i-audio-file", () => import("@icon-park/vue-next/es/icons/AudioFile")],
  ["i-bill", () => import("@icon-park/vue-next/es/icons/Bill")],
  ["i-blackboard", () => import("@icon-park/vue-next/es/icons/Blackboard")],
  ["i-branch-one", () => import("@icon-park/vue-next/es/icons/BranchOne")],
  ["i-brightness", () => import("@icon-park/vue-next/es/icons/Brightness")],
  ["i-camera-one", () => import("@icon-park/vue-next/es/icons/CameraOne")],
  ["i-carousel-video", () => import("@icon-park/vue-next/es/icons/CarouselVideo")],
  ["i-check", () => import("@icon-park/vue-next/es/icons/Check")],
  ["i-check-one", () => import("@icon-park/vue-next/es/icons/CheckOne")],
  ["i-clear", () => import("@icon-park/vue-next/es/icons/Clear")],
  ["i-click-to-fold", () => import("@icon-park/vue-next/es/icons/ClickToFold")],
  ["i-close", () => import("@icon-park/vue-next/es/icons/Close")],
  ["i-close-one", () => import("@icon-park/vue-next/es/icons/CloseOne")],
  ["i-close-small", () => import("@icon-park/vue-next/es/icons/CloseSmall")],
  ["i-code", () => import("@icon-park/vue-next/es/icons/Code")],
  ["i-color-filter", () => import("@icon-park/vue-next/es/icons/ColorFilter")],
  ["i-computer", () => import("@icon-park/vue-next/es/icons/Computer")],
  ["i-contrast-view", () => import("@icon-park/vue-next/es/icons/ContrastView")],
  ["i-copy", () => import("@icon-park/vue-next/es/icons/Copy")],
  ["i-cutting-one", () => import("@icon-park/vue-next/es/icons/CuttingOne")],
  ["i-dark-mode", () => import("@icon-park/vue-next/es/icons/DarkMode")],
  ["i-data", () => import("@icon-park/vue-next/es/icons/Data")],
  ["i-delete", () => import("@icon-park/vue-next/es/icons/Delete")],
  ["i-delete-one", () => import("@icon-park/vue-next/es/icons/DeleteOne")],
  ["i-document-folder", () => import("@icon-park/vue-next/es/icons/DocumentFolder")],
  ["i-dot", () => import("@icon-park/vue-next/es/icons/Dot")],
  ["i-download", () => import("@icon-park/vue-next/es/icons/Download")],
  ["i-edit", () => import("@icon-park/vue-next/es/icons/Edit")],
  ["i-editing", () => import("@icon-park/vue-next/es/icons/Editing")],
  ["i-editor", () => import("@icon-park/vue-next/es/icons/Editor")],
  ["i-emotion-happy", () => import("@icon-park/vue-next/es/icons/EmotionHappy")],
  ["i-erase", () => import("@icon-park/vue-next/es/icons/Erase")],
  ["i-exchange", () => import("@icon-park/vue-next/es/icons/Exchange")],
  ["i-expand-text-input", () => import("@icon-park/vue-next/es/icons/ExpandTextInput")],
  ["i-export", () => import("@icon-park/vue-next/es/icons/Export")],
  ["i-file-text", () => import("@icon-park/vue-next/es/icons/FileText")],
  ["i-film", () => import("@icon-park/vue-next/es/icons/Film")],
  ["i-filter", () => import("@icon-park/vue-next/es/icons/Filter")],
  ["i-fire", () => import("@icon-park/vue-next/es/icons/Fire")],
  ["i-flash-payment", () => import("@icon-park/vue-next/es/icons/FlashPayment")],
  ["i-flashlamp", () => import("@icon-park/vue-next/es/icons/Flashlamp")],
  ["i-flashlight", () => import("@icon-park/vue-next/es/icons/Flashlight")],
  ["i-flask", () => import("@icon-park/vue-next/es/icons/Flask")],
  ["i-fog", () => import("@icon-park/vue-next/es/icons/Fog")],
  ["i-folder-close", () => import("@icon-park/vue-next/es/icons/FolderClose")],
  ["i-folder-open", () => import("@icon-park/vue-next/es/icons/FolderOpen")],
  ["i-full-screen-one", () => import("@icon-park/vue-next/es/icons/FullScreenOne")],
  ["i-ghost", () => import("@icon-park/vue-next/es/icons/Ghost")],
  ["i-github", () => import("@icon-park/vue-next/es/icons/Github")],
  ["i-github-one", () => import("@icon-park/vue-next/es/icons/GithubOne")],
  ["i-go-end", () => import("@icon-park/vue-next/es/icons/GoEnd")],
  ["i-go-start", () => import("@icon-park/vue-next/es/icons/GoStart")],
  ["i-good-two", () => import("@icon-park/vue-next/es/icons/GoodTwo")],
  ["i-hard-disk", () => import("@icon-park/vue-next/es/icons/HardDisk")],
  ["i-heartbeat", () => import("@icon-park/vue-next/es/icons/Heartbeat")],
  ["i-inbox", () => import("@icon-park/vue-next/es/icons/Inbox")],
  ["i-info", () => import("@icon-park/vue-next/es/icons/Info")],
  ["i-landscape", () => import("@icon-park/vue-next/es/icons/Landscape")],
  ["i-lightning", () => import("@icon-park/vue-next/es/icons/Lightning")],
  ["i-loading-four", () => import("@icon-park/vue-next/es/icons/LoadingFour")],
  ["i-lock", () => import("@icon-park/vue-next/es/icons/Lock")],
  ["i-logout", () => import("@icon-park/vue-next/es/icons/Logout")],
  ["i-magic", () => import("@icon-park/vue-next/es/icons/Magic")],
  ["i-memory-card-one", () => import("@icon-park/vue-next/es/icons/MemoryCardOne")],
  ["i-menu-unfold-one", () => import("@icon-park/vue-next/es/icons/MenuUnfoldOne")],
  ["i-moon", () => import("@icon-park/vue-next/es/icons/Moon")],
  ["i-music", () => import("@icon-park/vue-next/es/icons/Music")],
  ["i-notebook", () => import("@icon-park/vue-next/es/icons/Notebook")],
  ["i-notes", () => import("@icon-park/vue-next/es/icons/Notes")],
  ["i-pause", () => import("@icon-park/vue-next/es/icons/Pause")],
  ["i-pencil", () => import("@icon-park/vue-next/es/icons/Pencil")],
  ["i-peoples-two", () => import("@icon-park/vue-next/es/icons/PeoplesTwo")],
  ["i-permissions", () => import("@icon-park/vue-next/es/icons/Permissions")],
  ["i-pic", () => import("@icon-park/vue-next/es/icons/Pic")],
  ["i-platte", () => import("@icon-park/vue-next/es/icons/Platte")],
  ["i-play", () => import("@icon-park/vue-next/es/icons/Play")],
  ["i-playback-progress", () => import("@icon-park/vue-next/es/icons/PlaybackProgress")],
  ["i-plus", () => import("@icon-park/vue-next/es/icons/Plus")],
  ["i-preview-open", () => import("@icon-park/vue-next/es/icons/PreviewOpen")],
  ["i-receive", () => import("@icon-park/vue-next/es/icons/Receive")],
  ["i-redo", () => import("@icon-park/vue-next/es/icons/Redo")],
  ["i-reduce-one", () => import("@icon-park/vue-next/es/icons/ReduceOne")],
  ["i-refresh", () => import("@icon-park/vue-next/es/icons/Refresh")],
  ["i-reverse-rotation", () => import("@icon-park/vue-next/es/icons/ReverseRotation")],
  ["i-right", () => import("@icon-park/vue-next/es/icons/Right")],
  ["i-ring", () => import("@icon-park/vue-next/es/icons/Ring")],
  ["i-round", () => import("@icon-park/vue-next/es/icons/Round")],
  ["i-save", () => import("@icon-park/vue-next/es/icons/Save")],
  ["i-search", () => import("@icon-park/vue-next/es/icons/Search")],
  ["i-setting-config", () => import("@icon-park/vue-next/es/icons/SettingConfig")],
  ["i-setting-one", () => import("@icon-park/vue-next/es/icons/SettingOne")],
  ["i-setting-two", () => import("@icon-park/vue-next/es/icons/SettingTwo")],
  ["i-shake", () => import("@icon-park/vue-next/es/icons/Shake")],
  ["i-share", () => import("@icon-park/vue-next/es/icons/Share")],
  ["i-snowflake", () => import("@icon-park/vue-next/es/icons/Snowflake")],
  ["i-star", () => import("@icon-park/vue-next/es/icons/Star")],
  ["i-sun-one", () => import("@icon-park/vue-next/es/icons/SunOne")],
  ["i-switch-themes", () => import("@icon-park/vue-next/es/icons/SwitchThemes")],
  ["i-text", () => import("@icon-park/vue-next/es/icons/Text")],
  ["i-theme", () => import("@icon-park/vue-next/es/icons/Theme")],
  ["i-time", () => import("@icon-park/vue-next/es/icons/Time")],
  ["i-tips", () => import("@icon-park/vue-next/es/icons/Tips")],
  ["i-to-bottom", () => import("@icon-park/vue-next/es/icons/ToBottom")],
  ["i-tool", () => import("@icon-park/vue-next/es/icons/Tool")],
  ["i-translate", () => import("@icon-park/vue-next/es/icons/Translate")],
  ["i-tree-diagram", () => import("@icon-park/vue-next/es/icons/TreeDiagram")],
  ["i-undo", () => import("@icon-park/vue-next/es/icons/Undo")],
  ["i-upload", () => import("@icon-park/vue-next/es/icons/Upload")],
  ["i-upload-one", () => import("@icon-park/vue-next/es/icons/UploadOne")],
  ["i-video", () => import("@icon-park/vue-next/es/icons/Video")],
  ["i-video-file", () => import("@icon-park/vue-next/es/icons/VideoFile")],
  ["i-view-list", () => import("@icon-park/vue-next/es/icons/ViewList")],
  ["i-volume-mute", () => import("@icon-park/vue-next/es/icons/VolumeMute")],
  ["i-volume-notice", () => import("@icon-park/vue-next/es/icons/VolumeNotice")],
  ["i-zoom-in", () => import("@icon-park/vue-next/es/icons/ZoomIn")],
  ["i-zoom-out", () => import("@icon-park/vue-next/es/icons/ZoomOut")],
] as const;

export function registerIconPark(app: App) {
  for (const [name, loader] of iconLoaders) {
    app.component(
      name,
      defineAsyncComponent({
        loader: async () => (await loader()).default,
        delay: 0,
        suspensible: false,
      }),
    );
  }
}
